# =============================================================================
# Python Environment for FSE Lab #3 (Apache Ant)
# Base: python:3.11-slim (Debian-based)
# Purpose: Execution and automation of Ant build scripts and SVN integration
# =============================================================================

FROM eclipse-temurin:21-jdk AS jbuilder
RUN jlink \
    --add-modules java.base,jdk.javadoc,jdk.compiler,java.sql,java.naming \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /javadoc-minimal

FROM python:3.11-slim

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  subversion \
  # adding git for reading .gitignore file
  # without suffer (lazy solution)
  git \
  make \
  ant \
  ant-optional && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY src/main/resources/python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  # for ant's "music" goal
  libasound2 \ 
  # for Apache Ivy installation
  unzip \
  curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Apache Ivy installation
RUN curl -o ivy.zip https://dlcdn.apache.org//ant/ivy/2.5.3/apache-ivy-2.5.3-bin.zip && \
  unzip ivy.zip && \
  mkdir -p /ant/lib && \
  mv apache-ivy-2.5.3/ivy-2.5.3.jar /ant/lib

# Docker CLI & Compose installation
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    lsb-release && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update && apt-get install -y \
    docker-ce-cli \
    docker-compose-plugin && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Javadoc Integration
COPY --from=jbuilder /javadoc-minimal /opt/javadoc-minimal
RUN ln -s /opt/javadoc-minimal/bin/javadoc /usr/local/bin/javadoc