# =============================================================================
# Python Environment for FSE Lab #3 (Apache Ant)
# Base: python:3.11-slim (Debian-based)
# Purpose: Execution and automation of Ant build scripts and SVN integration
# =============================================================================

FROM python:3.11-slim

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  subversion \
  make \
  ant \
  ant-optional && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY src/main/resources/python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  # for ant's "music" goal
  libasound2 \ 
  # for Apache Ivy installation
  unzip \
  curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Apache Ivy installation
RUN curl -o ivy.zip https://dlcdn.apache.org//ant/ivy/2.5.3/apache-ivy-2.5.3-bin.zip && \
  unzip ivy.zip && \
  mkdir -p ~/.ant/lib && \
  mv apache-ivy-2.5.3/ivy-2.5.3.jar ~/.ant/lib