name: Update Docker Images

on:
  push:
    branches: [dev]

jobs:
  docker_changes:
    runs-on: ubuntu-latest
    env:
      WATCH_LIST: "docker/"
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      full_image_dev: ${{ steps.get_image.outputs.full_image_dev }}
      full_image_web: ${{ steps.get_image.outputs.full_image_web }}
      full_image_pdf: ${{ steps.get_image.outputs.full_image_pdf }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Check for changes since the last push in WATCH_LIST
        id: filter
        run: |
          if git diff --quiet ${{ github.event.before }} ${{ github.event.after }} -- $WATCH_LIST; then
            echo "docker=false" >> $GITHUB_OUTPUT
            echo "No changes detected in: $WATCH_LIST"
          else
            echo "docker=true" >> $GITHUB_OUTPUT
            echo "Changes detected in: $WATCH_LIST"
          fi

      - name: Set full image names
        id: get_image
        run: |
          IMAGE_PDF=$(cat docker/IMAGE_PDF)
          IMAGE_WEB=$(cat docker/IMAGE_WEB)
          IMAGE_DEV=$(cat docker/IMAGE_DEV)
          echo "full_image_pdf=ghcr.io/${OWNER,,}/${IMAGE_PDF}:dev" >> $GITHUB_OUTPUT
          echo "full_image_web=ghcr.io/${OWNER,,}/${IMAGE_WEB}:dev" >> $GITHUB_OUTPUT
          echo "full_image_dev=ghcr.io/${OWNER,,}/${IMAGE_DEV}:dev" >> $GITHUB_OUTPUT
        env:
          OWNER: '${{ github.repository_owner }}'

  build_docker:
    needs: docker_changes
    if: needs.docker_changes.outputs.docker == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker Development image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.dev
          push: true
          tags: ${{ needs.docker_changes.outputs.full_image_dev }}
      
      - name: Build and push Docker Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: ${{ needs.docker_changes.outputs.full_image_web }}

      - name: Build and push Docker PDF image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.report
          push: true
          tags: ${{ needs.docker_changes.outputs.full_image_pdf }}